node_js:
 -"0.8"
 -"0.10"
before_install:
 - clang --version
 - clang++ --version
 - git submodule update --init --recursive
 - cd ./emscripten
 - git checkout master
 - ./emcc --help
 - ./emcc -O2 tests/hello_world.c -o teste.js
 - node teste.js
 - cd ..
 - make install
